graphData/urls.py
from django.urls import path
from . import views

app_name = 'graphData'

urlpatterns = [
    path('', views.top, name='top'),
    path('index', views.index, name='index'),
    path('<int:id>/delete/', views.delete, name='delete'),
    path('graphData/<str:category>/',
         views.graphData_category, name='graphData_category'),
    path('new_category/', views.new_category, name='new_category'),
    path('new_graphData/', views.new_graphData, name='new_graphData'),
]

register/urls.py
from django.urls import path
from . import views

app_name = 'register'

urlpatterns = [
    path('via', views.Top.as_view(), name='top'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('user_create/', views.UserCreate.as_view(), name='user_create'),
    path('user_create/done', views.UserCreateDone.as_view(),
         name='user_create_done'),
    path('user_create/complete/<token>/',
         views.UserCreateComplete.as_view(), name='user_create_complete'),
    path('user_detail/<int:pk>/', views.UserDetail.as_view(), name='user_detail'),
    path('user_update/<int:pk>/', views.UserUpdate.as_view(), name='user_update'),
    path('password_change/', views.PasswordChange.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDone.as_view(),
         name='password_change_done'),
    path('password_reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDone.as_view(),
         name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/',
         views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password_reset/complete/', views.PasswordResetComplete.as_view(),
         name='password_reset_complete'),
    path('email/change/', views.EmailChange.as_view(), name='email_change'),
    path('email/change/done/', views.EmailChangeDone.as_view(),
         name='email_change_done'),
    path('email/change/complete/<str:token>/',
         views.EmailChangeComplete.as_view(), name='email_change_complete'),
]

studyapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('register.urls')),
    path('', include('graphData.urls')),
]

graphData/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.core.validators import MaxValueValidator, MinValueValidator


class Category(models.Model):
    title = models.CharField('カテゴリ', max_length=20)

    def __str__(self):
        return self.title


class GraphData(models.Model):
    title = models.CharField('タイトル', max_length=50, help_text='勉強タイトル')
    studyDay = models.DateField('勉強日', help_text='勉強日')
    category = models.ForeignKey(
        Category, on_delete=models.PROTECT, help_text='学習した勉強のカテゴリ')
    details = models.CharField(
        '詳細', max_length=400, help_text='勉強の詳細')
    studyTime = models.FloatField('学習時間', help_text='学習時間', validators=[
                                  MinValueValidator(0.0, '時間を入力してください！'),
                                  MaxValueValidator(24.0, '24時間以内で記入してください！')])
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

    def __str__(self):
        return self.title

graphData/forms.py
from django.forms import ModelForm
from django import forms
from .models import Category, GraphData


class CategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = ['title']


class GraphDataForm(ModelForm):

    def __init__(self, *args, **kwd):
        super(GraphDataForm, self).__init__(*args, **kwd)
        self.fields["details"].required = False

    class Meta:
        model = GraphData
        fields = ['title', 'studyDay', 'category', 'details', 'studyTime']
        widgets = {  # プルダウン選択
            'studyDay': forms.SelectDateWidget
        }

graphData/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import GraphData, Category
from .forms import CategoryForm, GraphDataForm
from django.contrib.auth.decorators import login_required


def top(request):
    datas = GraphData.objects.all().order_by('studyDay')
    params = {
        'datas': datas
    }
    return render(request, 'top.html', params)


@login_required
def index(request):
    graphData = GraphData.objects.order_by('studyDay')
    return render(request, 'graphData/index.html', {'graphData': graphData})


@login_required
def delete(request, id):
    graphData = get_object_or_404(GraphData, pk=id)
    graphData.delete()
    return redirect('graphData:index')


@login_required
def graphData_category(request, category):
    category = Category.objects.get(title=category)
    graphData = GraphData.objects.filter(category=category).order_by('title')
    params = {'graphData': graphData, 'category': category}
    return render(request, 'graphData/index.html', params)


@login_required
def new_category(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('graphData:index')
    else:
        form = CategoryForm
    return render(request, 'graphData/new_category.html', {'form': form})


@login_required
def new_graphData(request):
    if request.method == 'POST':
        form = GraphDataForm(request.POST)
        if form.is_valid():
            graphData = form.save(commit=False)
            graphData.user = request.user
            form.save()
            return redirect('graphData:index')
    else:
        form = GraphDataForm
    return render(request, 'graphData/new_graphData.html', {'form': form})

templates/graphData/index.html
{% extends 'base.html' %} {% block content %}
<h2>カテゴリー</h2>
<ul>
  <a href="{% url 'graphData:index' %}">
    <li>全部</li>
  </a>

  {% for category in category_list %}
  <a href="{% url 'graphData:graphData_category' category %}">
    <li>{{ category }}</li>
  </a>
  {% endfor %}
</ul>
<a href="{% url 'graphData:new_category' %}">カテゴリーを追加する</a>
<h2>学習データ</h2>
{% if category %}
<h2>カテゴリー: {{ category.title }}</h2>
{% endif %}
{% for graphDatas in graphData %}
{% if request.user.id == graphDatas.user.id %}
<ul>
  <li>
    <h4>{{ graphDatas.title }}</h4>
    <h4>{{ graphDatas.studyTime }}時間</h4>
    <p>{{ graphDatas.details }}</p>
    <p>{{ graphDatas.studyDay }}</p>
  </li>
  <form method="POST" action="{% url 'graphData:delete' graphDatas.pk %}">
    {% csrf_token %}
    <button type="submit">削除</button>
  </form>
</ul>
{% endif %}
{% endfor %}
<a href="{% url 'graphData:new_graphData' %}">学習データを追加する</a>
{% endblock %}

templates/graphData/new_category.html
{% extends 'base.html' %} {% block content %}
<h2>カテゴリー</h2>
<a href="{% url 'graphData:index' %}">戻る</a>
<form action="{% url 'graphData:new_category' %}" method="POST">
  {% csrf_token %}
  {{ form.title }}
  <button>保存</button>
</form>
{% endblock %}

templates/graphData/new_graphData.html
{% extends 'base.html' %} {% block content %}
<h2>学習データ</h2>
<form action="{% url 'graphData:new_graphData' %}" method="POST">
  {% csrf_token %} {{ form.title }}<br />勉強タイトル<br />
  {{ form.category }}<br />学習した勉強のカテゴリ<br />
  {{ form.studyDay }}<br />学習日<br />
  {{ form.details }}<br />勉強の詳細<br />
  {{ form.studyTime }}時間<br />学習時間<br />
  {{ form.studyTime.errors }}
  <button>保存</button>
</form>
<a href="{% url 'graphData:index' %}">戻る</a>
{% endblock %}