register/urls.py
from django.urls import path
from . import views

app_name = 'register'

urlpatterns = [
    path('via', views.Top.as_view(), name='top'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('user_create/', views.UserCreate.as_view(), name='user_create'),
    path('user_create/done', views.UserCreateDone.as_view(),
         name='user_create_done'),
    path('user_create/complete/<token>/',
         views.UserCreateComplete.as_view(), name='user_create_complete'),
    path('user_detail/<int:pk>/', views.UserDetail.as_view(), name='user_detail'),
    path('user_update/<int:pk>/', views.UserUpdate.as_view(), name='user_update'),
    path('password_change/', views.PasswordChange.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDone.as_view(),
         name='password_change_done'),
    path('password_reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDone.as_view(),
         name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/',
         views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password_reset/complete/', views.PasswordResetComplete.as_view(),
         name='password_reset_complete'),
    path('email/change/', views.EmailChange.as_view(), name='email_change'),
    path('email/change/done/', views.EmailChangeDone.as_view(),
         name='email_change_done'),
    path('email/change/complete/<str:token>/',
         views.EmailChangeComplete.as_view(), name='email_change_complete'),
]

studyapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('register.urls')),
    path('', include('graphData.urls')),
]

register/models.py
from django.db import models
from django.core.mail import send_mail
from django.contrib.auth.models import PermissionsMixin, UserManager
from django.contrib.auth.base_user import AbstractBaseUser
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone


class CustomUserManager(UserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email address'), unique=True)
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=150, blank=True)

    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_(
            'Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = CustomUserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_full_name(self):
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        send_mail(subject, message, from_email, [self.email], **kwargs)

    @property
    def username(self):
        return self.email

register/forms.py
from django import forms
from django.contrib.auth.forms import (
    AuthenticationForm, UserCreationForm, PasswordChangeForm, PasswordResetForm, SetPasswordForm
)
from django.contrib.auth import get_user_model

User = get_user_model()


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label


class UserCreateForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    def clean_email(self):  # 何度でも仮登録をできるようにするため
        email = self.cleaned_data['email']
        User.objects.filter(email=email, is_active=False).delete()
        return email


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('last_name', 'first_name',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class MyPasswordChangeForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class MyPasswordResetForm(PasswordResetForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class MySetPasswordForm(SetPasswordForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class EmailChangeForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    def clean_email(self):  # 何度でも仮登録を以下略
        email = self.cleaned_data['email']
        User.objects.filter(email=email, is_active=False).delete()
        return email

register/views.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView,
    PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView,
    PasswordResetCompleteView
)
from django.urls import reverse_lazy
from django.core.mail import send_mail
from django.contrib.sites.shortcuts import get_current_site
from django.core.signing import BadSignature, SignatureExpired, loads, dumps
from django.http import HttpResponseBadRequest
from django.shortcuts import redirect, resolve_url
from django.template.loader import render_to_string
from django.views import generic
from .forms import (
    LoginForm, UserCreateForm, UserUpdateForm, MyPasswordChangeForm,
    MyPasswordResetForm, MySetPasswordForm, EmailChangeForm
)

User = get_user_model()


class Top(generic.TemplateView):
    template_name = 'viapage.html'


class Login(LoginView):
    form_class = LoginForm
    template_name = 'register/login.html'


class Logout(LoginRequiredMixin, LogoutView):
    template_name = 'top.html'


class UserCreate(generic.CreateView):
    template_name = 'register/user_create.html'
    form_class = UserCreateForm

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.save()

        current_site = get_current_site(self.request)
        domain = current_site.domain
        context = {
            'protocol': self.request.scheme,
            'domain': domain,
            'token': dumps(user.pk),
            'user': user,
        }

        subject = render_to_string(
            'register/mail_template/create/subject.txt', context).strip()
        message = render_to_string(
            'register/mail_template/create/message.txt', context)

        user.email_user(subject, message)
        return redirect('register:user_create_done')


class UserCreateDone(generic.TemplateView):
    template_name = 'register/user_create_done.html'


class UserCreateComplete(generic.TemplateView):
    template_name = 'register/user_create_complete.html'
    timeout_seconds = getattr(
        settings, 'ACTIVATION_TIMEOUT_SECONDS', 60*60*24)  # 1日以内

    def get(self, request, **kwargs):
        token = kwargs.get('token')
        try:
            user_pk = loads(token, max_age=self.timeout_seconds)

        except SignatureExpired:
            return HttpResponseBadRequest()

        except BadSignature:
            return HttpResponseBadRequest()

        else:
            try:
                user = User.objects.get(pk=user_pk)
            except User.DoesNotExits:
                return HttpResponseBadRequest()
            else:
                if not user.is_active:
                    user.is_active = True
                    user.save()
                    return super().get(request, **kwargs)

        return HttpResponseBadRequest()


class OnlyYouMixin(UserPassesTestMixin):
    raise_exception = True

    def test_func(self):
        user = self.request.user
        return user.pk == self.kwargs['pk'] or user.is_superuser


class UserDetail(OnlyYouMixin, generic.DetailView):
    model = User
    template_name = 'register/user_detail.html'


class UserUpdate(OnlyYouMixin, generic.UpdateView):
    model = User
    form_class = UserUpdateForm

    def get_success_url(self):
        return resolve_url('register:user_detail', pk=self.kwargs['pk'])


class PasswordChange(PasswordChangeView):
    form_class = MyPasswordChangeForm
    success_url = reverse_lazy('register:password_change_done')
    template_name = 'register/password_change.html'


class PasswordChangeDone(PasswordChangeDoneView):
    template_name = 'register/password_change_done.html'


class PasswordReset(PasswordResetView):
    subject_template_name = 'register/mail_template/password_reset/subject.txt'
    email_template_name = 'register/mail_template/password_reset/message.txt'
    template_name = 'register/password_reset_form.html'
    form_class = MyPasswordResetForm
    success_url = reverse_lazy('register:password_reset_done')


class PasswordResetDone(PasswordResetDoneView):
    template_name = 'register/password_reset_done.html'


class PasswordResetConfirm(PasswordResetConfirmView):
    form_class = MySetPasswordForm
    success_url = reverse_lazy('register:password_reset_complete')
    template_name = 'register/password_reset_confirm.html'


class PasswordResetComplete(PasswordResetCompleteView):
    template_name = 'register/password_reset_complete.html'


class EmailChange(LoginRequiredMixin, generic.FormView):
    template_name = 'register/email_change_form.html'
    form_class = EmailChangeForm

    def form_valid(self, form):
        user = self.request.user
        new_email = form.cleaned_data['email']

        current_site = get_current_site(self.request)
        domain = current_site.domain
        context = {
            'protocol': 'https' if self.request.is_secure() else 'http',
            'domain': domain,
            'token': dumps(new_email),
            'user': user,
        }

        subject = render_to_string(
            'register/mail_template/email_change/subject.txt', context).strip()
        message = render_to_string(
            'register/mail_template/email_change/message.txt', context)
        send_mail(subject, message, None, [new_email])

        return redirect('register:email_change_done')


class EmailChangeDone(LoginRequiredMixin, generic.TemplateView):
    template_name = 'register/email_change_done.html'


class EmailChangeComplete(LoginRequiredMixin, generic.TemplateView):
    template_name = 'register/email_change_complete.html'
    timeout_seconds = getattr(
        settings, 'ACTIVATION_TIMEOUT_SECONDS', 60*60*24)

    def get(self, request, **kwargs):
        token = kwargs.get('token')
        try:
            new_email = loads(token, max_age=self.timeout_seconds)

        except SignatureExpired:
            return HttpResponseBadRequest()

        except BadSignature:
            return HttpResponseBadRequest()

        else:
            User.objects.filter(email=new_email, is_active=False).delete()
            request.user.email = new_email
            request.user.save()
            return super().get(request, **kwargs)

templates/register/email_change_complete.html
{% extends "base.html" %}
{% block content %}
<p>
    メールアドレスを変更しました。<br>
</p>
{% endblock %}

templates/register/email_change_form.html
{% extends "base.html" %}
{% block content %}
<form action="" method="POST">
  {{ form.non_field_errors }}
  {% for field in form %}
  <div class="form-group">
    <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
    {{ field }}
    {{ field.errors }}
  </div>
  {% endfor %}
  {% csrf_token %}
  <button type="submit" class="btn btn-primary btn-lg">送信</button>
</form>
{% endblock %}

templates/register/login.html
{% extends "base.html" %}
{% block content %}
<div class="row">
  <div class="card col-md-6">
    <div class="card-body">
      <form action="{% url 'register:login' %}" method="POST">
        {{ form.non_field_errors }} {% for field in form %} {{ field }}
        {{ field.errors }}
        <hr />
        {% endfor %}
        <button type="submit" class="btn btn-success btn-lg btn-block">
          ログイン
        </button>
        <input type="hidden" name="next" value="{{ next }}" />
        {% csrf_token %}
      </form>
    </div>
  </div>

  <div class="card col-md-6">
    <div class="card-body">
      <a
        href="{% url 'register:user_create' %}"
        class="btn btn-success btn-lg btn-block"
        >会員登録</a
      >
      <a
        href="{% url 'register:password_reset' %}"
        class="btn btn-success btn-lg btn-block"
        >パスワードを忘れた方</a
      >
    </div>
  </div>
</div>
{% endblock %}

templates/register/password_change.html
{% extends "base.html" %}
{% block content %}
<form action="" method="POST">
  {{ form.non_field_errors }}
  {% for field in form %}
  <div class="form-group">
    <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
    {{ field }}
    {{ field.errors }}
  </div>
  {% endfor %}
  {% csrf_token %}
  <button type="submit" class="btn btn-primary btn-lg">送信</button>
</form>
{% endblock %}

templates/register/password_change_done.html
{% extends "base.html" %}
{% block content %}
<p>
  パスワードを変更しました。
  <br />
  <a class="btn btn-primary btn-lg" href="{% url 'register:login' %}"
    >ログイン</a
  >
</p>
{% endblock %}

templates/register/password_reset_complete.html
{% extends "base.html" %}
{% block content %}
<p>
    パスワード再設定を完了しました。<br>
    <a class="btn btn-primary btn-lg" href="{% url 'register:login' %}">ログイン</a>
</p>
{% endblock %}

templates/register/password_reset_confirm.html
{% extends "base.html" %}
{% block content %}
<form action="" method="POST">
  {{ form.non_field_errors }}
  {% for field in form %}
  <div class="form-group">
    <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
    {{ field }}
    {{ field.errors }}
  </div>
  {% endfor %}
  {% csrf_token %}
  <button type="submit" class="btn btn-primary btn-lg">送信</button>
</form>
{% endblock %}

templates/register/password_reset_done.html
{% extends "base.html" %}
{% block content %}
<p>
    パスワード再設定用のメールを送信しました。
    <br>
    メールに記載されているリンクから再設定を行ってください。
</p>
{% endblock %}

templates/register/password_reset_form.html
{% extends "base.html" %}
{% block content %}
<form action="" method="POST">
  {{ form.non_field_errors }}
  {% for field in form %}
  <div class="form-group">
    <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
    {{ field }}
    {{ field.errors }}
  </div>
  {% endfor %}
  {% csrf_token %}
  <button type="submit" class="btn btn-primary btn-lg">送信</button>
</form>
{% endblock %}

templates/register/top.html
{% extends "base.html" %} {% block content %}
<p>ここに、好きな内容を入れる。</p>
<canvas id="canvas"></canvas>

<script>
  var ctx = document.getElementById("canvas").getContext("2d");
  var myBar = new Chart(ctx, {
    type: "bar",
    data: {
      labels: ["A", "B", "C", "D", "E"], //ラベルをDjangoのTODO登録から設定したい日にちにする予定
      datasets: [
        {
          data: [5, 20, 11, 2, 30], //数字をDjangoのTODO登録から設定したい学習時間にする予定
          backgroundColor: [
            //DjangoのTODO登録から設定したいグラフの色を変更する
            "#FF4444",
            "#4444FF",
            "#44BB44",
            "#FFFF44",
            "#FF44FF"
          ]
        }
      ]
    },
    options: {
      responsive: true,
      legend: {
        display: false
      },
      title: {
        display: true,
        fontSize: 18,
        text: "〇〇月の学習時間"
      },
      scales: {
        yAxes: [
          {
            display: true,
            scaleLabel: {
              display: true,
              labelString: "学習時間",
              fontSize: 18
            },
            ticks: {
              min: 0,
              max: 30,
              fontSize: 18,
              stepSize: 5
            }
          }
        ],
        xAxes: [
          {
            display: true,
            barPercentage: 0.4,
            categoryPercentage: 0.4,
            scaleLabel: {
              display: true,
              labelString: "日にち",
              fontSize: 18
            },
            ticks: {
              fontSize: 18
            }
          }
        ]
      },
      layout: {
        padding: {
          left: 100,
          right: 50,
          top: 0,
          bottom: 0
        }
      }
    }
  });
</script>
{% endblock %}

templates/register/user_create.html
{% extends "base.html" %}
{% block content %}
<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-lg">送信</button>
</form>
{% endblock %}

templates/register/user_create_done.html
{% extends "base.html" %}
{% block content %}
<p>
    会員登録確認メールを送信しました。まだ、会員登録は完了していません。
    <br>
    確認メールを送信しましたので、確認メールに記載されているリンクから本登録を行ってください。
</p>
{% endblock %}

templates/register/user_detail.html
{% extends "base.html" %}
{% block content %}
<table class="table">
  <tbody>
    <tr>
      <th>ユーザー名</th>
      <td>{{ user.email }}</td>
    </tr>
    <tr>
      <th>姓</th>
      <td>{{ user.last_name }}</td>
    </tr>
    <tr>
      <th>名</th>
      <td>{{ user.first_name }}</td>
    </tr>
  </tbody>
</table>
{% endblock %}

templates/register/user_form.html
{% extends "base.html" %}
{% block content %}
<form action="" method="POST">
  {{ form.non_field_errors }}
  <table class="table">
    <tbody>
      {% for field in form %}
      <tr>
        <th><label for="{{ field.id_for_label }}">{{ field.label }}</label></th>
        <td>{{ field }} {{ field.errors }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% csrf_token %}
  <button type="submit" class="btn btn-success btn-lg">送信</button>
</form>
{% endblock %}