graphData/urls.py
from django.urls import path
from . import views

app_name = 'graphData'

urlpatterns = [
    path('', views.top, name='top'),
    path('index', views.index, name='index'),
    path('<int:id>/delete/', views.delete, name='delete'),
    path('graphData/<str:category>/',
         views.graphData_category, name='graphData_category'),
    path('new_category/', views.new_category, name='new_category'),
    path('new_graphData/', views.new_graphData, name='new_graphData'),
]

register/urls.py
from django.urls import path
from . import views

app_name = 'register'

urlpatterns = [
    path('via', views.Top.as_view(), name='top'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('user_create/', views.UserCreate.as_view(), name='user_create'),
    path('user_create/done', views.UserCreateDone.as_view(),
         name='user_create_done'),
    path('user_create/complete/<token>/',
         views.UserCreateComplete.as_view(), name='user_create_complete'),
    path('user_detail/<int:pk>/', views.UserDetail.as_view(), name='user_detail'),
    path('user_update/<int:pk>/', views.UserUpdate.as_view(), name='user_update'),
    path('password_change/', views.PasswordChange.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDone.as_view(),
         name='password_change_done'),
    path('password_reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDone.as_view(),
         name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/',
         views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password_reset/complete/', views.PasswordResetComplete.as_view(),
         name='password_reset_complete'),
    path('email/change/', views.EmailChange.as_view(), name='email_change'),
    path('email/change/done/', views.EmailChangeDone.as_view(),
         name='email_change_done'),
    path('email/change/complete/<str:token>/',
         views.EmailChangeComplete.as_view(), name='email_change_complete'),
]

studyapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('register.urls')),
    path('', include('graphData.urls')),
]

templates/base.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
      integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4"
      crossorigin="anonymous"
    />
    <script
      type="text/javascript"
      src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js"
    ></script>

    <title>学習管理サイト</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'graphData:top' %}">学習管理サイト</a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          {% if user.is_authenticated %}
          <li>
            <a
              class="nav-item nav-link"
              href="{% url 'register:user_detail' user.pk %}"
              >ユーザー情報閲覧</a
            >
          </li>
          <li>
            <a
              class="nav-item nav-link"
              href="{% url 'register:user_update' user.pk %}"
              >ユーザー情報更新</a
            >
          </li>
          <li>
            <a class="nav-item nav-link" href="{% url 'register:logout' %}"
              >ログアウト</a
            >
          </li>
          <li>
            <a
              class="nav-item nav-link"
              href="{% url 'register:password_change' %}"
              >パスワードの変更</a
            >
          </li>
          <li>
            <a
              class="nav-item nav-link"
              href="{% url 'register:email_change' %}"
              >メールアドレスの変更</a
            >
          </li>
          <li>
            <a
              class="nav-item nav-link"
              href="{% url 'graphData:index' %}"
              >カテゴリ別学習時間</a
            >
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-item nav-link" href="{% url 'register:login' %}">
              ログインはこちら
            </a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <div class="container mt-3">
      {% block content %}{% endblock %}
    </div>

    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
      integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
      integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/top.html
{% extends "base.html" %} {% block content %} 
{% if request.user.is_authenticated %}

<canvas id="canvas"></canvas>
<script>
  var ctx = document.getElementById("canvas").getContext("2d");
  var myBar = new Chart(ctx, {
    type: "bar",
    data: {
      labels: [
        {% for data in datas %}
        {% if request.user.id == data.user.id %}
        "{{ data.studyDay }}",
        {% endif %}
        {% endfor %}
      ], //ラベルをDjangoのTODO登録から設定したい日にちにする予定
      datasets: [
        {
          data: [
          {% for data in datas %}
          {% if request.user.id == data.user.id %}
          {{ data.studyTime }},
          {% endif %}
          {% endfor %}
          ]            
          //数字をDjangoのTODO登録から設定したい学習時間にする予定
          // backgroundColor: [
          //   //DjangoのTODO登録から設定したいグラフの色を変更する
          //   "#FF4444",
          //   "#4444FF",
          //   "#44BB44",
          //   "#FFFF44",
          //   "#FF44FF"
          // ]
        }
      ]
    },
    options: {
      responsive: true,
      legend: {
        display: false
      },
      title: {
        display: true,
        fontSize: 18,
        text: "〇〇月の学習時間"
      },
      scales: {
        yAxes: [
          {
            display: true,
            stacked: true,
            scaleLabel: {
              display: true,
              labelString: "学習時間",
              fontSize: 18
            },
            ticks: {
              min: 0,
              max: 24,
              fontSize: 18,
              stepSize: 5
            }
          }
        ],
        xAxes: [
          {
            display: true,
            stacked: true,
            barPercentage: 0.4,
            categoryPercentage: 0.4,
            scaleLabel: {
              display: true,
              labelString: "日にち",
              fontSize: 18
            },
            ticks: {
              fontSize: 18
            }
          }
        ]
      },
      layout: {
        padding: {
          left: 100,
          right: 50,
          top: 0,
          bottom: 0
        }
      }
    }
  });
</script>
{% else %}
<h2>ログインをしましょう</h2>
<a href="{% url 'register:login' %}"> ログインはこちらから</a>{% endif %} 
{% endblock %}

templates/viapage.html
<!-- 緊急避難先:エラーの解決法が分かれば削除するhtml -->
<!-- django.urls.exceptions.NoReverseMatch
django.urls.exceptions.NoReverseMatch: Reverse for 'top' not found. 'top' is not a valid view function or pattern name. -->
{% extends "base.html" %} {% block content %}
<meta http-equiv="refresh" content=" 0; url=./" />
{% endblock %}